definitions:
  request.UserCountAddRequest:
    properties:
      count:
        type: integer
    type: object
  request.UserCreateRequest:
    properties:
      name:
        type: string
    type: object
  response.UserCountAddResponse:
    properties:
      count:
        type: integer
    type: object
  response.UserCreateResponse:
    properties:
      token:
        type: string
    type: object
  response.UserDestroyResponse:
    properties:
      message:
        type: string
    type: object
  response.UserGetResponse:
    properties:
      count:
        type: integer
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/count:
    post:
      consumes:
      - application/json
      description: ユーザーのカウントを追加します
      parameters:
      - description: UserCountAddRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserCountAddRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserCountAddResponse'
      summary: ユーザーのカウントを追加
  /user/create:
    post:
      consumes:
      - application/json
      description: ユーザーを作成します
      parameters:
      - description: UserCreateRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserCreateResponse'
      summary: ユーザーの作成
  /user/destroy:
    post:
      consumes:
      - application/json
      description: ユーザーを削除します
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserDestroyResponse'
      summary: ユーザーの削除
  /user/get:
    post:
      consumes:
      - application/json
      description: ユーザーを取得します
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserGetResponse'
      summary: ユーザーの取得
swagger: "2.0"
