name: CI

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Run go fmt
      run: |
        cd app
        go fmt ./...

    - name: Run go mod tidy
      run: |
        cd app
        go mod tidy

    - name: Run tests
      run: |
        cd app
        go test ./...
